name: tarka_ui
description: Tarka UI Kit is a pre-built component library for building Flutter apps. It is based on our design system, utilizing Atomic Design principles.
version: 1.1.2
issue_tracker: https://github.com/tarkalabs/tarka-ui-kit-flutter/issues
homepage: https://github.com/tarkalabs/tarka-ui-kit-flutter.git
topics: [design-system,ui-kit]

environment:
  sdk: '^3.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluentui_system_icons: ^1.1.226

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  golden_toolkit: ^0.15.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Bold.ttf