name: tarka_ui
description: Flutter package for Tarka Kit Design System
version: 1.0.0
homepage: https://github.com/tarkalabs/tarka-ui-kit-flutter.git

environment:
  sdk: '>=3.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluentui_system_icons: ^1.1.226

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  golden_toolkit: ^0.15.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Bold.ttf